# Generated by Django 3.0.4 on 2020-03-26 13:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_auto_20200326_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time_end',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
