# Generated by Django 3.0.4 on 2020-04-03 15:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_auto_20200326_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomsAvailable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number1', models.CharField(max_length=100)),
                ('time_start1', models.TimeField(default=django.utils.timezone.now)),
                ('time_end1', models.TimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
