# Generated by Django 3.0.4 on 2020-04-03 15:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_roomsavailable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomsavailable',
            name='time_end1',
        ),
        migrations.RemoveField(
            model_name='roomsavailable',
            name='time_start1',
        ),
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start1', models.TimeField(default=django.utils.timezone.now)),
                ('time_end1', models.TimeField(default=django.utils.timezone.now)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.RoomsAvailable')),
            ],
        ),
    ]
