# Generated by Django 3.0.4 on 2020-04-03 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_auto_20200403_2053'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoomsAvailable',
            new_name='Room',
        ),
        migrations.RenameModel(
            old_name='Slots',
            new_name='Slot',
        ),
    ]
