# Generated by Django 3.0.7 on 2020-06-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_auto_20200403_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='status',
            field=models.CharField(default='available', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time_end',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time_start',
            field=models.CharField(max_length=50),
        ),
    ]
