# Generated by Django 3.0.7 on 2020-06-21 13:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0009_auto_20200620_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='slot',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
